services:
  db:
    image: postgres:latest
    container_name: 01blog-db
    environment:
      POSTGRES_USER: abdnour
      POSTGRES_PASSWORD: abdnour
      POSTGRES_DB: mainDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: 01blog-backend
    env_file: ./backend/.env
    environment:
      DB_URL: jdbc:postgresql://db:5432/mainDB
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: 01blog-frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
